version: '3.7'

networks:
  default:

volumes:
  tmp_volume:
  rechat-external-mongodb-data:
    external: true

services:
  php_tools_worker: &php_tools_worker
    build:
      context: ../
      target: app
      dockerfile: ./docker/debug/Dockerfile_php_tools_worker
    restart: always
    container_name: rechat_php_tools_worker
    networks:
      - default
    volumes:
      - &app-data ../:/app
      - &tmp tmp_volume:/tmp
    environment:
      WORKER_NAME: tools
      PHP_IDE_CONFIG: serverName=docker-rechat-php-workers
      REMOTE_HOST: 172.29.128.1
    depends_on:
      - mongo
      - beanstalkd

  php_rechat_worker:
    <<: *php_tools_worker
    restart: always
    container_name: rechat_php_rechat_worker
    volumes:
      - *app-data
      - *tmp
    environment:
      WORKER_NAME: rechat
    depends_on:
      - mongo
      - beanstalkd

  node_discord_worker: &node_discord_worker
    build:
      context: ../
      target: app
      dockerfile: ./docker/debug/Dockerfile_node_bot
    restart: always
    container_name: node_discord_worker
    networks:
      - default
    volumes:
      - *app-data
      - *tmp
    environment:
      WORKER_NAME: worker
    depends_on:
      - mongo
      - beanstalkd

  node_discord_bot:
    <<: *node_discord_worker
    restart: always
    container_name: node_discord_bot
    volumes:
      - *app-data
      - *tmp
    environment:
      WORKER_NAME: bot
    depends_on:
      - mongo
      - beanstalkd

  beanstalkd:
    image: bodsch/docker-beanstalkd
    container_name: rechat_beanstalkd
    networks:
      - default
    restart: always
    ports:
      - 11300:11300

  mongo:
    image: mongo
    networks:
      - default
    restart: always
    container_name: rechat_mongodb
    volumes:
      - rechat-external-mongodb-data:/data/db
    ports:
      - 27017:27017
