version: '3.7'

networks:
  default:

volumes:
  app_volume:
  rechat-external-mongodb-data:
    external: true
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/d/MongoDB_WSL/

services:
  beanstalkd:
    image: bodsch/docker-beanstalkd
    container_name: rechat_beanstalkd
    networks:
      - default

  php_tools_worker: &php_tools_worker
    build:
      context: ../
      target: app
      dockerfile: ./docker/debug/Dockerfile_php_tools_worker
    restart: always
    container_name: rechat_php_tools_worker
    networks:
      - default
    volumes:
      - &php-app-data app_volume:/app
    environment:
      WORKER_NAME: tools
      PHP_IDE_CONFIG: serverName=docker-rechat-php-workers
      REMOTE_HOST: host.docker.internal
    env_file:
      ../.env
    depends_on:
      - mongo

  php_rechat_worker:
    <<: *php_tools_worker
    restart: always
    container_name: rechat_php_rechat_worker
    volumes:
      - *php-app-data
    environment:
      WORKER_NAME: rechat
    depends_on:
      - mongo

  mongo:
    image: mongo
    networks:
      - default
    restart: always
    container_name: rechat_mongodb
    volumes:
      - rechat-external-mongodb-data:/mnt/d/MongoDB_WSL/data
    ports:
      - 27017:27017
