# This stage installs our modules
FROM mhart/alpine-node:latest
WORKDIR /app/src/RechatToolDiscordBot/
COPY package.json package-lock.json ./

# If you have native dependencies, you'll need extra tools
# RUN apk add --no-cache make gcc g++ python

RUN npm ci --prod

COPY --from=0 /app .
COPY . .
CMD ["node", "src/worker.js"]